name: Build and push Docker image for projectors
on:
  push:
    branches: [trunk]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Login to docker.pkg.github.com
        run: echo ${{ secrets.GH_DOCKER_REGISTRY_PAT }} | docker login docker.pkg.github.com -u ${{ secrets.GH_DOCKER_REGISTRY_USERNAME }} --password-stdin
      - run: docker build -f projectors.Dockerfile -t docker.pkg.github.com/thomastoye/weewoo/projectors:latest .
      - run: docker image tag docker.pkg.github.com/thomastoye/weewoo/projectors:latest docker.pkg.github.com/thomastoye/weewoo/projectors:${{ github }}-${{ github.run_id }}-${{ github.run_number }}
      - run: docker push docker.pkg.github.com/thomastoye/weewoo/projectors:latest
      - run: docker push docker.pkg.github.com/thomastoye/weewoo/projectors:${{ github }}-${{ github.run_id }}-${{ github.run_number }}
